import '../app/data/models/product_model.dart';
import 'constants.dart';

class DummyHelper {
  const DummyHelper._();

  static List<ProductModel> products = [
        ProductModel(
        id: 1,
        image: Constants.product11,
        name: 'Laptop Table',
        quantity: 0,
        price: 29.99,
        rating: 4.0,
        reviews: '5.8k reviews',
        size: '4.5',
        isFavorite: false),
    ProductModel(
        id: 2,
        image: Constants.product7,
        name: 'Laptop Bag',
        quantity: 0,
        price: 19.99,
        rating: 4.0,
        reviews: '5.8k reviews',
        size: '4.5',
        isFavorite: false),
    ProductModel(
        id: 3,
        image: Constants.product8,
        name: 'Laptop portable Table',
        quantity: 0,
        price: 59.99,
        rating: 4.0,
        reviews: '5.8k reviews',
        size: '4.5',
        isFavorite: false),
    ProductModel(
        id: 4,
        image: Constants.product9,
        name: 'Laptop Bag',
        quantity: 0,
        price: 9.99,
        rating: 4.0,
        reviews: '5.8k reviews',
        size: '4.5',
        isFavorite: false),
    ProductModel(
        id: 5,
        image: Constants.product11,
        name: 'Laptop Table',
        quantity: 0,
        price: 19.99,
        rating: 4.0,
        reviews: '5.8k reviews',
        size: '4.5',
        isFavorite: false),
    ProductModel(
      id: 6,
      image: Constants.product1,
      name: 'The Nvidia Laptop',
      quantity: 0,
      price: 125.99,
      rating: 4.5,
      reviews: '1.2k reviews',
      size: '4.5',
      isFavorite: false,
    ),
    ProductModel(
        id: 7,
        image: Constants.product2,
        name: 'The MacBook Laptop',
        quantity: 0,
        price: 179.99,
        rating: 4.4,
        reviews: '10k reviews',
        size: '4.5',
        isFavorite: false),
    ProductModel(
        id: 8,
        image: Constants.product3,
        name: 'The Dell Laptop',
        quantity: 0,
        price: 159.99,
        rating: 4.3,
        reviews: '22k reviews',
        size: '4.5',
        isFavorite: false),
    ProductModel(
        id: 9,
        image: Constants.product4,
        name: 'The HP Laptop',
        quantity: 0,
        price: 89.99,
        rating: 4.2,
        reviews: '3.4k reviews',
        size: '4.5',
        isFavorite: false),
    ProductModel(
        id: 10,
        image: Constants.product5,
        name: 'The ROG Laptop',
        quantity: 0,
        price: 99.99,
        rating: 4.1,
        reviews: '2.6k reviews',
        size: '4.5',
        isFavorite: false),
  ];
}
